name: lesson_companion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.8.3
  desktop_window: ^0.4.0
  path_provider: ^2.0.11
  file_picker: ^5.2.1
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  shared_preferences: ^2.0.15
  flutter_speed_dial: ^6.2.0
  intl: ^0.17.0
  azlistview: ^2.0.0
  sticky_headers: ^0.3.0+2
  alphabet_scroll_view: ^0.3.2
  connectivity_plus:
  analyzer:
  storage_manager: ^0.1.10
  provider: ^6.0.5
  rich_text_controller: ^1.4.0
  printing:

dev_dependencies:
  build_runner: ^2.3.0
  isar_generator: ^3.0.2
  sqflite_common_ffi:
  test:

flutter:
  uses-material-design: true

  fonts:
    - family: Andika
      fonts:
        - asset: lib/assets/Andika-Regular.ttf
        - asset: lib/assets/Andika-Italic.ttf
          style: italic
        - asset: lib/assets/Andika-Bold.ttf
          weight: 700
        - asset: lib/assets/Andika-BoldItalic.ttf
          weight: 500
    - family: IBMPlexSansKR
      fonts:
        - asset: lib/assets/IBMPlexSansKR-Regular.ttf
        - asset: lib/assets/IBMPlexSansKR-Regular.ttf
          style: italic
        - asset: lib/assets/IBMPlexSansKR-Bold.ttf
          weight: 700
        - asset: lib/assets/IBMPlexSansKR-SemiBold.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: lib/assets/RobotoMono-Regular.ttf
